version: '3.8'

services:
  db:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: nextcloud
      MYSQL_USER: nextcloud
      MYSQL_PASSWORD: your_db_password
    volumes:
      - nextcloud_db_data:/var/lib/mysql

  nextcloud:
    image: nextcloud:latest
    depends_on:
      - db
      - redis
    environment:
      NEXTCLOUD_ADMIN_USER: admin
      NEXTCLOUD_ADMIN_PASSWORD: your_admin_password
      NEXTCLOUD_DB_TYPE: mysql
      NEXTCLOUD_DB_HOST: db
      NEXTCLOUD_DB_USER: nextcloud
      NEXTCLOUD_DB_PASSWORD: your_db_password
      NEXTCLOUD_REDIS_HOST: nextcloud_redis
    volumes:
      - nextcloud_nextcloud_data:/var/www/html
    networks:
      - nextcloud
    ports:
      - 8080:80

  redis:
    image: redis:alpine
    volumes:
      - nextcloud_redis_data:/data

volumes:
  nextcloud_db_data:
  nextcloud_nextcloud_data:
  nextcloud_redis_data:

networks:
  nextcloud:
    external: true
